### ISSUE TITLE
The notebook in docs/ doesn't display on Github

### ISSUE THREAD

**Issue by nsajko** [milankl/Jenks.jl#20]
Hi!

I think there's something wrong with the notebook, as it fails to load for me on Github. I get this message instead of the notebook:

> Sorry, something went wrong. Reload?

**Comment by milankl** [comment]
Yes, unfortunately, this is a common issue on github. This is not due to the notebook itself but the server that github uses to render the notebooks on its web interface. See [#3035](https://github.com/jupyter/notebook/issues/3035) and references therein.

Often just try `reload`, or wait a few hours. You can always also download the notebook and open it on your own notebook servers.

**Comment by milankl** [comment]
Now it works for me
![image](https://user-images.githubusercontent.com/25530332/110673174-5be35700-81c8-11eb-897c-fc22a5667a61.png)

**Comment by nsajko** [comment]
It works now for me too! Sorry for wasting your time!

**Comment by milankl** [comment]
Don't worry, I haven't worked on this repo for a while, let me know if you face any other issues. You are also always welcome to create a pr when you see scope for improvement
